Add controllers
maximboltinov/ShareIt pull request #1
Opened 2024-02-27 04:06 UTC by maximboltinov

2024-02-27 17:31 UTC, YazykovMikhail requested changes

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        return "ошибка валидации, указаны не все параметры или некорректный email";
Возвращай или Мапу или создай отдельный класс для отправки ответов об ошибках.
Мапа отправляется оптому что она превразается в json, просто текст в json не превратится

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * TODO Sprint add-controllers.
Убирай комментарии todo там где реализовал код, todo говорит о том, что нужно реализовать

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Запрос POST /items");
логирой входящие данные, проверь везде

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    public Item update(Long ownerId, @Validated Item item) {
В методы репозитория должен приходить только итем, других зависимостей быть не должно. 
Итем должен быть уже в сервисе подготовленным

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +}
Тут как раз должен быть 
	private User owner;

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +}
Связь обьектов, что бы каждый итем знал чей он.

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    }
логи

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    }
логи

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +
Хороший способ проверять уникальность емейла
`	private final Set<String> emailUniqSet = new HashSet<>();`
	
И как раз вот так буде твыглядит метод add


```
	public User save(User user) {
		final String email = user.getEmail();
		if (emailUniqSet.contains(email)) {
			throw new DataAlreadyExistException("Email: " + email + " already exists");
		}
		user.setId(++counter);
		storage.put(user.getId(), user);
		emailUniqSet.add(email);
		return user;
	}
```

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +
Это как индексы в базах данных. Смысл такой же, в даннм случае индекс уникальности)
Соответсвенно для метода обновления так же

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +    public User update(@Validated User user) {
@Validated  - в репозитории не работает, он нужен только в контроллере, именно там проиходит валидация данных

2024-02-27 17:31 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
Эти аннотации не нужны для моделей, только для dto которые приходят в контроллер

2024-02-29 23:20 UTC, maximboltinov commented
Ориентируясь не тесты, создал отдельный dto для возврата Item - ItemOutDto. Исключив поле userId (id владельца вещи)

2024-03-01 13:42 UTC, YazykovMikhail approved these changes

2024-03-08 14:14 UTC, merged